{{- if .Values.imageVectorOverwrite }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gardener-extension-cri-resmgr-installation-imagevector-overwrite
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-cri-resmgr-installation
data:
  images_overwrite.yaml: |
{{ .Values.imageVectorOverwrite | indent 4 }}
{{- end }}
