{{- if .Values.configs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gardener-extension-cri-resmgr-configs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-cri-resmgr
data:
  {{- .Values.configs | toYaml | nindent 2 }}
{{- end }}
