{{- if .Values.configs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gardener-extension-cri-resmgr-configs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-cri-resmgr
data:
  {{- .Values.configs | toYaml | nindent 2 }}

{{/*
  {{- range $key, $elem := .Values.configs }} 
  {{ $key }}: | 
      {{ $elem | toYaml | nindent 2 }}
  {{- end }}
  # elem jest tutaj multline Yaml stringiem i musi taki pozostac
  {{- .Values.configs | toYaml | nindent 2 }}
foo: {{"put" | printf "%s%s" "out" | printf "%q"}}
  {{- range $key, $elem := .Values.configs }} 
  - {{ fromYaml $elem }}:
  {{- end }}

  {{- .Values.configs.fallback }}
  {{- .Values.configs | toYaml | nindent 2 }}
*/}}
  
{{- end }}
