linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 10
  gocritic:
    disabled-checks:
      - commentFormatting
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 4
  lll:
    line-length: 140
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  errcheck:
    exclude: ./.errcheck-exclude
  gocognit:
    min-complexity: 31
  gomoddirectives:
    replace-allow-list:
      # see https://github.com/dolthub/go-mysql-server/issues/1591
      - github.com/dolthub/go-mysql-server

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    ## - contextcheck
    ## - cyclop
    ## - decorder
    - depguard
    # - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    # - errchkjson
    - errname
    - errorlint
    ## - execinquery
    # - exhaustive
    ## - exhaustruct
    - exportloopref
    ## - forbidigo
    ## - forcetypeassert
    # - funlen
    # - gci
    # - gochecknoglobals
    # - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    # - gocyclo
    ## - godot
    # - godox
    ## - goerr113
    - gofmt
    # - gofumpt
    - goheader
    - goimports
    # - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    # - gosec
    - gosimple
    - govet
    ## - grouper
    - importas
    - ineffassign
    ## - interfacebloat
    # - interfacer
    # - ireturn
    # - lll
    - loggercheck
    ## - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    # - nilerr
    ## - nilnil
    # - nlreturn
    - noctx
    - nolintlint
    ## - nonamedreturns
    - nosprintfhostport
    ## - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    # - tagliatelle
    - tenv
    - testableexamples
    # - testpackage
    ## - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    # - varnamelen
    ## - wastedassign
    # - whitespace
    # - wrapcheck
    # - wsl

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - govet
        - dupl
        # - goerr113

run:
  concurrency: 4
  timeout: 5m
  build-tags:
    - ""
    - integration
  skip-dirs:
    - internal/proxyproto
  # use Go 1.17 linter behaviour because we don't use generics - see
  # https://github.com/golangci/golangci-lint/issues/2649 for details - this can
  # be removed once that issue is resolved, or if we decide to use generics -
  # the downside is some linters are disabled for 1.18
  go: '1.17'
