language: node_js
os:
  - linux
  - osx
addons:
  ssh_known_hosts:
    - github.com
node_js:
  - 10.22.1
  - 12.18.4

cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run lint
  - npm run test-with-coverage
