environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "12"
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run test-with-coverage
build: off
