name: matsciml
channels:
  - defaults
  - intel
  - dglteam
  - conda-forge
dependencies:
  - scipy
  - numba
  - numpy
  - mkl-devel=2024.0.0
  - intel-openmp=2024.0.0
  - dglteam::dgl=2.0.0
  - setuptools
  - pybind11
  - python=3.10
  - pip
  - pip:
    - "--index-url https://download.pytorch.org/whl/cpu"
    - intel-extension-for-pytorch==2.1.100
    - torch==2.1.2
    - "--extra-index-url https://pytorch-extension.intel.com/release-whl/stable/cpu/us/"
    - oneccl_bind_pt==2.1.0
variables:
  # append to library path for dynamic libraries
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib'"
  # use Intel OpenMP
  LD_PRELOAD: "'$LD_PRELOAD:$CONDA_PREFIX/lib/libiomp5.so'"
