name: matsciml
channels:
  - defaults
  - intel
  - dglteam
dependencies:
  - intel::scipy
  - intel::numba
  - intel::mkl-devel
  - intel::intel-openmp
  - intel::impi-devel
  - dglteam::dgl=2.0.0
  - setuptools
  - pybind11
  - pip
  - pip:
    - "--extra-index-url https://pytorch-extension.intel.com/release-whl-aitools/"
    - torch==2.0.1.a0
    - intel-extension-for-pytorch==2.0.120+xpu
    - oneccl_bind_pt==2.0.200+gpu
