name: matsciml
channels:
  - defaults
  - intel
  - dglteam
  - conda-forge
dependencies:
  - scipy
  - numba
  - numpy
  - mkl-devel=2024.0.0
  - intel-openmp=2024.0.0
  - dglteam::dgl=2.0.0
  - setuptools
  - pybind11
  - python=3.10
  - pip
  - pip:
    - "--extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/"
    - intel-extension-for-pytorch==2.1.10+xpu
    - torch==2.1.0a0
    - oneccl_bind_pt==2.1.100+xpu
