name: matsciml
channels:
  - defaults
  - intel
  - dglteam
  - conda-forge
dependencies:
  - scipy
  - numba
  - numpy
  - mkl-devel=2024.0.0
  - intel-openmp=2024.0.0
  - dglteam::dgl=2.0.0
  - setuptools
  - pybind11
  - pip
  - pip:
    - "--extra-index-url https://pytorch-extension.intel.com/release-whl-aitools/"
    - intel-extension-for-pytorch=2.0.120
    - pytorch=2.0.1
    - oneccl_bind_pt==2.0.200+gpu
