name: matsciml
channels:
  - dglteam
  - conda-forge
  - pyg
  - pytorch
dependencies:
  - scipy
  - numba
  - numpy
  - dglteam::dgl=2.0.0
  - setuptools
  - pybind11
  - python=3.11
  - pytorch::pytorch=2.3.0
  - pip
  - pip:
    - "-e ./[all]"
variables:
  # append to library path for dynamic libraries
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib'"
  # use Intel OpenMP
  LD_PRELOAD: "'$LD_PRELOAD:$CONDA_PREFIX/lib/libiomp5.so'"
