name: matsciml
channels:
  - conda-forge
  - pytorch
dependencies:
  - setuptools
  - pytorch::pytorch=2.4.0
  - pip
  - pip:
    - "-f https://data.pyg.org/whl/torch-2.4.0+cpu.html"
    - "-f https://data.dgl.ai/wheels/torch-2.4/repo.html"
    - "-e ./[all]"
    - intel-openmp
variables:
  # append to library path for dynamic libraries
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib'"
  # use Intel OpenMP
  LD_PRELOAD: "'$LD_PRELOAD:$CONDA_PREFIX/lib/libiomp5.so'"
