apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cri-rm-installation
  namespace: kube-system
  labels:
    app.kubernetes.io/name: cri-rm-installation
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cri-rm-installation
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cri-rm-installation
    spec:
      hostPID: true
      hostIPC: true
      containers:
      - name: container-runtime-cri-rm
        # TODO: replace with gardener-extension-cri-rm-installation + support for imagevector
        image: 100.64.176.37:5000/gardener-extension-cri-rm-installation:latest
        command: ["/scripts/install-cri-rm.sh"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-volume
          mountPath: /var/host
        - name: cri-rm-installation-script
          mountPath: /scripts
      initContainers:
      - name: prepare-docker
        image: debian
        command: ["/bin/bash", "-c"]
        args:
          -
            cp /scripts/config.toml /var/host/etc/containerd/config.toml;
            chroot /var/host bash -c "systemctl restart containerd"
        volumeMounts:
        - name: host-volume
          mountPath: /var/host
        - name: cri-rm-init
          mountPath: /scripts
      volumes:
      - name: host-volume
        hostPath:
          path: /
      - name: cri-rm-installation-script
        configMap:
          name: cri-rm-installation-script
          defaultMode: 0744
      - name: cri-rm-init
        configMap:
          name: cri-rm-init
          defaultMode: 0744
