# Copyright 2022 Intel Corporation. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: cri-rm-remove-script
  namespace: kube-system
  annotations:
    resources.gardener.cloud/ignore: "true"
data:
  remove-cri-rm.sh: |-
    #!/bin/bash
    # Remove cri-rm from kubelet configuration
    echo "Remove cri-rm from kubelet configuration"
    sed -i '/\[Unit\]/aAfter=containerd.service' /var/host/etc/systemd/system/kubelet.service
    sed -i 's/\/var\/run\/cri-resmgr\/cri-resmgr.sock/unix:\/\/\/run\/containerd\/containerd.sock/g' /var/host/etc/systemd/system/kubelet.service

    # Stop and disable cri-resource-manager
    echo 'Stop and disable cri-resource-manager'
    chroot /var/host bash -c "systemctl disable cri-resource-manager"
    chroot /var/host bash -c "systemctl stop cri-resource-manager"

    # Remove files left after cri-rm
    echo 'Remove files left after cri-rm'
    rm -rf /var/host/opt/intel
    rm -rf /var/host/etc/cri-resmgr
    rm -rf /var/host/etc/systemd/system/cri-resource-manager.service

    # Restart kubelet with new confugiration
    echo 'Restart kubelet with new configuration'
    chroot /var/host bash -c "systemctl daemon-reload"
    chroot /var/host bash -c "systemctl restart kubelet"

    # Check if kubelet is active
    echo 'Check if kubelet is active'
    while true; do
        kubeletIsActive=$(chroot /var/host bash -c "systemctl is-active kubelet")
        if [ "$kubeletIsActive" == "active" ];then
            break
        fi
    done

    # Sleep after successful removal 
    echo 'Uninstallation successful. Sleeping...'
    echo "cri-resource-manager successfully removed. Sleeping..."
    while true; do
        sleep 3600;
        echo "Still sleeping";
    done
