apiVersion: v1
kind: ConfigMap
metadata:
  name: extension-cri-resmgr-monitoring-scrape-config
  namespace: {{ namespace }}
  labels:
    extensions.gardener.cloud/configuration: monitoring
data:
  scrape_config: |
    - job_name: cri-rm
      honor_timestamps: true
      scrape_interval: 1m
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: https
      authorization:
        type: Bearer
        credentials_file: /var/run/secrets/gardener.cloud/shoot/token/token
      tls_config:
        ca_file: /etc/prometheus/seed/ca.crt
        insecure_skip_verify: false
      follow_redirects: true
      enable_http2: true
      relabel_configs:
      - separator: ;
        regex: (.*)
        target_label: __address__
        replacement: kube-apiserver:443
        action: replace
      - separator: ;
        regex: (.*)
        target_label: __metrics_path__
        replacement: /api/v1/namespaces/kube-system/services/cri-resmgr-installation:8891/proxy/metrics
        action: replace
      - separator: ;
        regex: (.*)
        target_label: type
        replacement: shoot
        action: replace
      kubernetes_sd_configs:
      - api_server: https://kube-apiserver:443
        role: node
        kubeconfig_file: ""
        authorization:
          type: Bearer
          credentials_file: /var/run/secrets/gardener.cloud/shoot/token/token
        tls_config:
          ca_file: /etc/prometheus/seed/ca.crt
          insecure_skip_verify: false
        follow_redirects: true
        enable_http2: true
