# SPDX-FileCopyrightText: Copyright Boozt Fashion, AB
# SPDX-License-Identifier: MIT

pre-commit:
  parallel: true
  commands:
    shellcheck:
      glob: "*.sh"
      run: |
        docker run --rm -v $(pwd):/mnt koalaman/shellcheck:stable {staged_files}
