---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: cri-resmgr-extension
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+0ba2/bODKf9SsIZxdoi1iW5ddBhwPOdbyt79oksNMW/bSgJdrWRRJ1JGXX2+5/vyEpybLj+JGk7u6eBkEs8zEczoszI3qKmUciwqrkiyAR92lUdZlfZYSHU1Y7exawADqtlvoE2PxUz/Vmo263282W1Tyz6q1mwz5DredZfjckXGCG0BmjVOwat6//TwrTnfLvzTAT5hKHwVPWkAJuN5sPyV+KHuRvtzp1q9Gp2yD/TqPVOEPWc21yF/yfy/8c9Wi8ZP50JpBt2TYaRIIE0MhiyrAAfTBRNwjQUI7gaEg4YXPimca5cY7e+S7oDPFQEnmEITEjqBtjFz7Sngv0kTCpVMg2LfRCDqikXZWXfwcMS5qgEC9RRAVKOAEUPkcTPyCIfHFJLJAfIZeGceDjyCVo4YuZWiZFAmSgzykKOhYYRmMYH8O3SXEcwkIRLGEmROzUaovFwsSKWJOyaS3QA3nt3aDXvxr1q0CwmvIhCgjniJH/Jj6DrY6XCMdAj4vHQGWAF4gyhKeMQJ+gkt4F84UfTS8QpxOxwIwAFs/ngvnjRKwxK6MO9lwcAOzCEap0R2gwqqDX3dFgdAE4Pg1u315/uEWfusNh9+p20B+h6yHqXV9dDm4H11fw7RfUvfqM/j24urxABFgFy5AvMZP0A5G+ZKMSHRoRskbAhGqCeExcf+K7sK9omuApQVM6JyyC7aCYsNDnUpgcyPMAS+CHvlA6wu9vyjQMHPup+B00rxsRDomDVt5l5XIMj3Boj4Ua2kVvSRAiV/oezVIwUVDBdCZNmEt4NcQR0Aes5yjHI0e/SR0aihn9D3GFYYhlDOumQpNLGPOMKsusg5ihK6ezUjfrbdOqGD/aME8Eu/2/IKAzWIBZPGWN48//TrNhlef/KeBQ+cfMp+DXlm6AOT8yIth7/rfa6vxvWR2rXa+fWXbDtlvl+X8KKM//8vw/xfnPgdFeEgAi8+5v3PRpDSKCOz/yHHSTupaedC1GSAT2sMCOgZCOGHa6KGOOgwQG1fOjxJgGdIyDSzLBSSAcNMEBJ+sRRiVbEil3lm8/jx3ylYrxivlXDAoO9f/S7EGw2HVpEh2ZEu7P/+yV/7fa0v83ICUs/f8JoPT/pf8/Uf6nvf1IO5KudiRHu3s9ioPgYOjXr8gckoBgWO4qa0a//w6jAjwmAZdYkZSXeZeMYR8EXJk8ew5Z6Udb5mngUP//64wEoAHcFPHRtcA9/t9qtFX8b8EZ3rA60v/LBLD0/6eAr1+rCHlk4kfgmv0QTL6CqsqCZI8/QTPMbxj0f0EVPsN2q+1UkPlRBl1gSXK8KfAU5TMgT4zEBFV+5v/8mW+OZCSm3BeULXehALsl2xA6j0YYefJL4fFHc/2PA4faPxtj97EvAvbYf7PdaK3iv1ZH2r/dLOO/k0AZ/5Xx3/eK/6rV6loMqHwITsQMcu/ftG5t1gJ6AdgjYUMakC2hYe6juJn5LdMNaOI5+4LGp4eD22eqdxPRtlhUHjMsAd1xjCpM9N8wmsSKAvk15vCQv8zQrR6JA7oMSSSKnSqu1QPk0lVApUxQUgT/x2nflAj1GYAeqYcFFu5MPcXq6VFE7F/gHtoHZXR/LVcL+5ELYS9VR0am0niKCnV/rTCRmhpNF2Q8o/TOpdHEnyZ60mEEyKckBoUkmnhGsscHGHwEJ7yIM+JS5j2SFzm6vSvp12Ze3rq+XuVV5T7ySuU+mjwJ+/5ashq68bUGpieSw4UXb4rxoJ1qTQlxrJfnBAQvUlLm981kKwddCqL1o90aqlzHBrZUyZ7mSF9DA2j+X8Gfwm6GZCKXzTi8gxkw6v6h8tSt82Qs3yorr761oPGcZYwTxH+Hxv+5GVRVgjUHHlBWlcGBDHfIztRgX/7fstP3v3XI/1sy/4csoIz/TwJplr+WPX9Uwr3OZCs1cWspr6d04j2Oj63ibdehE9b2MloVHfzXdTV20DdDrr6LJd8g0Af8AjX/5JWFQ+1/FRceXwXYY/+Q9je0/XesZtNugP3bzU6ztP9TQJn/l/n/Kd7/yGxzFZ1e5t7kD/wCSDLDUXH63Jd9b0FElC3fyV07yFI9ShG4JiQ9L9LGnowGNSkcKJTHhyYmlGnIuwJ1j4+gM/ecIi5wUmGNwKq0eLKmvKq/77zPhoN5uHc8CWuPOM8VV/wIsnyPoBeqjo9+Mm9Tms3XILQbDPZcOSi4rLxEJhy7+h0EUFSksnD+6oZgjb1PSVEyJZAQFy+qXB2IQIq/mCAcPg+4Ij0aWFBGQPVAC9GgeLkmhOwFj1lknmq7SYLghoLeLtd0Wb9MifPO4jwSzR+tVtlGBu+7b/of+73b6+Gv1x/7w0/DwW0/HwWpsL7cU1N3gQtxWm1r4LapDxsaUqBPKxzfRhL4018Gb0a7yVlpfoppx9JwfIXgL53CSrutKR84p0ESkvdSax624B1b2aQNXITEJY3u2E08Ur4Pxflb6dmUcWEcI9i7jgJQTsES8rDda47lzNrHqocY5WaJjVOg4ZC8Zh3RPfKO4uJhPHw0qftE4+n7c++pB6iatnV/Tz86dC3hGeD4+k+q40ekgfvqP211/1vf/7cb6v53p17Wf04CD7vIZy75rFzjqYs8coub+/sGudpnUGB4iNJKjp1dGKm9QvB5ruYxyIMI+klPkxReZF+AE0KW/5Hzj+0HjERQnAmtTqEpn5+Rkk8qHBqvat+7urTb/ud6X0/8Aege+2901P0PWf+pW7a8/1XvtO3y/tdJoKz/lPWf71X/0QmorpOk1/TgKLFNn8998C5kCg5zT2VBFjnw1EEqCJEv1+JCotoNFnjJDcM4Pz9H/wJDlmwjXzDsk0gFmNEF2oyxZYjtwrAxkT8Qnfse8FvuPv2RqdqNnqSwpr8i0ZmfkpO6KukpvVQJizmlCNToTjILdIOEYyLftqa9aaKq09Pze9ToMsk3pZl6pKOeD0r0q0WaU+UuMus8TZ1WvA+oi4MZ5cJpWVZ9X01nE/thRMEmIvH81Gi0RrG45qA6iB7dXqPXffRh1L+Uj71hv3vbT7P4990bJdzVD4QxzxIbLVIOCOQIfSZLAx6T36Qn8uRQjEDBZKM0Aga6ko2TU+RPkvkMTgVupOe+VPUJpXUpUbnZCaNhYW39g+bCkYr0KJ+B5gbyAq6uOBFA56kGQzfQUFomREaGXqBx3ALgVNBihoW+zTsnKITt+wq/ShbB9aZXOTbQy8oFkXyu7FuoYqxy0SwR1cpSUR4d/sDawINU0k5YxkFjzNIlm172ay29sjS923SiLMQMB5f9XHCxLkUpmh7QV01hMXxRaPXMjMCuK/w5kCgotNPpsoqVs9ad2UE3LF7S0NC7+eCgTssKVQvMnBKW9V6ScQI6n13tyH6lfuHKg+ZCr3+R98oKH6OaNi8J8xxeR9kO+LCJY766mIDPc1686KnLIC+/vRiSEBRSPiQR/P+gbrPAwwgiGaE+afzypfmqzNBLKKGEEkoooYQSStiE/wFve8rSAFAAAA==
  ## Example values for development/testing puropses
  values:
    #replicaCount: 0            # for development purposes (if you want to start with "make start")
    image:
      repository: localhost:5001/gardener-extension-cri-resmgr
      tag: pawelbranch
      pullPolicy: Always
    imageVectorOverwrite: |
      images:
      - name: gardener-extension-cri-resmgr-installation
        tag: pawelbranch
        repository: localhost:5001/gardener-extension-cri-resmgr-installation
    configs:
      foo2: |
        foo-2-from-ctrldeploy
      foo3: |
        foo-3-from-ctrldeploy
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: cri-resmgr-extension
spec:
  deployment:
    deploymentRefs:
    - name: cri-resmgr-extension
  resources:
  - kind: Extension
    type: cri-resmgr-extension
    globallyEnabled: false
    reconcileTimeout: "60s"
