---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: cri-rm-extension
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+1a3W/bNhDPs/4KwkVfBkiRZFseDAxYlm7tgKIImqHY20BLZ5sLJQok5dYN+r/vSFmKYsex63juF38PNk0eeSfeB+9Ez6jMoADpwwcNhWKi8FPJfJmfnx0NIWI0HNpvxPq3bUeDeBgmUdwPo7MwGgz7yRkZHk+E7aiUppKQMymEfoxu1/g3itlW/V/OqdTBkub8qTyMgpPBYKv+41GE+o8StJFB3/RHyWCE+g+P8YC78IPrn5bsHUij9zFZxF5BcxiT2gLuTMLLQGFfqS3ZBXkFPCepsQ+iBWEFbiHn9SxQopIpKD+nBZ2BJFSRdh1D/XJlcKSU4l9ItefpZYk8aVlyllLDwls0EoVBFIQeDrUy9qIgSoKw533pjftOsN3/NeQlpxrUk0+CPeP/YDgMYyQ0/j8cuPh/Euyj/wxKLpY5FAceBzviP6p+1Og/7MdIF0dJFLn4fwp04z/GWXW+iLwbVmRj8qLVupeDphnVdOwRUp8QW81mRaFKmiLZ7S0J3gIHqiB403STT5+QitMJcGVWJIZxcFNNQBaA9hYwcb6LiyohNXMlLJjpf8WUFnL5muVM47FhR+x5omoh3lFe4cqrzktRFboWQ6F0KU6tBcmpTuevO5IdIhshjeusFu3sngG/t/5hHFDw1Q4YlJIJyfTyklOl3uwx2Ty3XLAULtLU7MV+c1JRaMqQoBXe38McarAcswGrC1akvMqA9GxXjwS1IjpkVxXnVwIVtbynPDsWlO1gd14qckw4srtN9cn5bqF84vtonJmhMWaAJL9MKVfw42QX+8T/xrxSY14HHAG78v9+FJv4H0aYJkQx1n9x3I+GLv6fAt34r9I5ZBVnxSy4+dkGovYwuOpGmM86DxbGecckalM9b8bFhPIXMKUVx2BdO9y9CqPXsCPW5MhUSKLncFc7tFyaWiVwBcFh2Mf/V2cFrc+Kzw8AO+v/JGn8v98fxMb/B/2B8/9T4F7933j79b3k4CtM/770rn0/2Mf//5kDL9FIAl0e9C5w5/nf8f9wlJj6L0xi5/+nwO2tT0gGU0zr24zctx5qRtiUzKm6kjj+gfTUnMbDZNxby8g1nZF2BuaKhZ6S3nP163O1Tonll1DMFGqPLYFxAR5acHzwgkVmfnSaX3rXvx7s4/9yQtOnXATs8P9+Mmz8Pwpj854wxjzA5f8nwTNyffXib/8PxuFSlEvJZnP9F9rCmMQYhsn1xRW5/p1g/k0L+4NOp4wzNAtTcpe0WOJAdpeYm1cEkk0qdEnlPfNWq7/GZKJQ4P+JRJpNGcgxucBcYA5+HISe5/u+101ErMHRSs+xCPhorwQ2CpJLjooD+VZweCA/aY1ZBY2BBykXVTZ+LHN5Wk7y8Cx7OVI8lAyZOCQrDsjQx4nspRRVabn79k2cfYe1uk2pe+/ew3YHbWJVExjWPi5lEnaQ2IWfk9XYDLT95kzVjffmXZdtlbZ1kBC7GWwsu1U3m7zSWskHMqJZzpRhJGGGpLJrSJu88kojQTF7D5O5EDdoyFM2q+pJ+wlgWlWJhgi18BKa5pYN/oydyAolIRUyO3Av2uV2cqrv7bK29z6/3k+9zcV7vc1l2irg/7eSO9K1n+foerraX3nluhr3etLaUnJa1uwVoOL1SpTFpps8uIOpQNWy4nELtaFjbbWVkT0tgP6GHWj533Icxad4C1PDstnZRzYBqTYPkac8sqom5irbRvIHK+hj1c3HP/+353+LOp8+wh9AdtV/0aC/9v+fZBSNXP53CtT3MvV92aqUMn8ECZhasHyGJ2eAed6jVylYao2JLRSMnZedu5sL/p4ulSu2HBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHI6J/wDgcTYCAFAAAA==
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: cri-rm-extension
spec:
  deployment:
    deploymentRefs:
    - name: cri-rm-extension
  resources:
  - kind: Extension
    type: cri-rm-extension
    globallyEnabled: false
