---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: cri-resmgr-extension
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+0ca2/bODKf/SsI5xZoi1jx2wfdl3MTb+u75gEnbdFPBS3Rti6SqCUpu952//vNkJKsOI5fSd3urgZFLInkzHBenKGojqlwWchEhX1RLJQeDyuO8CqCyWAsTo+eBaoAnVZL/wIs/+rrWrNRq7fbzVa1eVSttZqN+hFpPQ/59RBLRQUhR4Jzta7fpvY/KYzX6v9sQoWy5jTwn0IDFdxuNh/TP6oe9F9vdWrVRqdWB/13Gq3GEak+1yTXwd9c/8fkjEdz4Y0nitSr9Trph4r58FBEXFAF9mCRru+TAfaQZMAkE1PmWqXj0jF55zlgM8wlcegyQdSEkW5EHfhJWk7IBybQqEjdqpIX2KGcNJVf/gswzHlMAjonIVcklgxQeJKMPJ8R9sVhkSJeSBweRL5HQ4eRmacmmkyCBNggnxIUfKgo9KbQP4K7Ub4foUozjDBRKrJPT2ezmUU1sxYX41PfdJSn7/pnvcubXgUY1kPehz6Tkgj2W+wJmOpwTmgE/Dh0CFz6dEa4IHQsGLQpjvzOhKe8cHxCJB+pGRUMsLieVMIbxuqesFLuYM75DiAuGpJy94b0b8rkdfemf3MCOD72b99evb8lH7uDQffytt+7IVcDcnZ1ed6/7V9dwt2vpHv5ify3f3l+QhiICsiwL5FA/oFJD8WoVUduGLvHwIgbhmTEHG/kOTCvcBzTMSNjPmUihOmQiInAk6hMCey5gMX3Ak9pG5EPJ2WVSjTyEvXbZForhTRgNllEl0XIKblMwvNI6a5d8pb5AXEw9hiRgouCCSYjeSwcJisBDYE/EL0kGR7s/SYJaCQS/H/MUaWSmkdAN1EakihNU66qVg3UDE0Zn+WaVWtb1XLpRzvmgWB9/FcMbIYqcIun0Nh9/e80G9Vi/T8EbKv/SHgc4trc8amUO2YEG9f/Vluv/61qp9qu1Y6q9Ua93irW/0NAsf4X6/8h1n8JgnZjHxBZd/+UlsdPISO480LXJtdJaDnD0FIKmKIuVdQuEWIyhrUhqjSlfgydatlSUhr7fEj9czaisa9sMqK+ZPczjHJKkuhwlk0/yx0ySvl8xforJgXbxn90e1AsdRwehzuWhJvrv/oi/lfbGP8bUBIW8f8AUMT/Iv4fqP4z0f7GBJKuCSQ7h3vTS4LioOvXr8QaMJ9RIHeZPiZ//AG9fDpkvkSsBPVl3cVDmAeDUIZrzzaUfrRnHga2jf+fJ8wHC5CWinbeC9wQ/6uNts7/q7CGN6odjP9YABbx/xDw9WuFEJeNvBBCsxeAy5dJRXsQtngjMqHyWkD7F1KWE1pvte0ysT5g0gWehP0tRcckGwF1YqhGpPyL/PcvcrmnYBGXnuJivg4F+C1bhdDeG2Ho4k3u8kdL/eeBbf1fDKmz74uADf7fbDdai/yv1UH/rzeL/O8gUOR/Rf73vfK/SqVyLwfUMYTGagK19+/Gtpb3As588EcmBtxnK1LDLEZJK41bluPz2LU3JY1PTwdXj9TvJsJVuSguMyIG27FLFRjovRE8jjQHeBtJuMheZpinLot8Pg9YqPKNOq81HZB0BVBpF0SO4O8waRszpX99sCN9MaPKmeirSF/txcRmAg/QPqqjh7Qco+w9CVE3MUfBxug8eYN6SCuI0VLD8YwNJ5zfOTwceePYDNqOAbyKIzBIZpgXLL18RMA7SMINpWAOF+6essjQbaRkXpu52dP79Mqvyg+Rl8sP0WRF2Pe3kkXXpdtTcD0Vb6+8aFmNW83UWEpAI0NeMlC8SliZPnSTlRJ0OKjWC9dbqA4dS9gSI3taIH0ND8Dy/wrxFGYzYCMkm0p4jTCg18NF5alTl/EQ3yrrqL5yQ+M5tzEOkP9tm/9nblDRBdYUZMBFBZMDTHfY2tJgU/3fqifvf2tQ/7ew/ocqoMj/DwJJlX+vev6glXuV6hYtceVW3pm2iQsa7bqLt9qGDri3l/Kq+ZCf75uxTb6VkPo6kXyDRB/wK9L8k+8sbOv/i7xw912ADf4PZX/D+H+n2mzWG+D/9WanWfj/IaCo/4v6/xDvf7DaXGSn51k0+YlfAKEwbJ2nTz1sewsq4mL+Dmdtk6pu0YYgDSPJepE8PMNs0LAigUNcPgwzAZYh73Lc7Z9Bp+E5QZyTpMYaglcZ9aSPsl39Tet92h3cw7mTcXC6x3qupeKFUOW7jLzQ+/jkH9ZtwrP1GpR2TcGfy1sll+WXxIJl17yDAI7yXObWX/PAvyfep5QoqREgRPmDKpdbIkD15wuE7ceBVDCigQelDFS29BADWpb3lJC+4LHywtPPrmPfv+Zgt/N7tmxepkRZY34cC6d7m1U6kf5F903vQ+/s9mrw+epDb/Bx0L/tZb2gFDaHe071WeBcnna6MnFbtoclC8nxZwxOrmIJ4umv/Tc369lZWH6CaQ1pWL4CiJd2jtJ6b8o6TrkfB+wCreZxD14zlWXeIEQgLnS6XSexp34fy/NX8rOs41w/wah7FfpgnErE7HG/NxLLhLVJVI8JykkLGzvHwzZ1zX1ED9jbSYrbyXBvVjepxjXn5y64C6ia9erDOf3o1LWAZ4Dd938SG9+hDNy0/2PO/2H9V4PrFp7/a3c6Rf13CHg8RD7zls8iNB56kwenuDy/b1CrfQIDhosw2cmp/8l3cvaD9f4/NVJ74gegm85/4GYv+n+j1my12vr7n3bx/cdhoNj/KfZ/vtf+T34nxCa1Uun4+JjcXp1f2YQMehdQYZEhA9KMBEyMkQYIMKD4rk53/Q/4JkqCfaHAOkOdTvjMJMTIAllOoDF/dmDAkOHXn1PPBWHi1JIvSDWrZpDGn3wiYso6rQR9DtLVRqerEWvMCdjIHRIExbNgyPBVatKaVKGm9tRzm3AQpgmauu7zlDJmgQcVwXrBkbJcm5R5yLCeAZP2ufkytbwSM7nWKyRxufGTEFHjkqU0vQoBGyOgbJAQ1EhGmUyiDZ66kOL7PNK9oxh8GkwcDcDsDWiPWJyhtDUfPiBVdqtarW0oU3GwomMYhRmi0vdRbh+h68/oXKbEluocfMmCA8xEDSdbbW9U8spMXHqZi/0n9RD7dkzBJEL1/NwYtJv9Ju84mM7NIFTSUH89bVx6ntZzqXVyHR3UhCoyjD0fjAVDhMtnoc8p+o00PjcSPAD+tQGWkAvyukfe3/TO8fJs0Ove9pItk4vutTa9xdfYVC5RBQTYwyRhyNyQ/Y5h38WuFFie40P0EAG+m/bDIfj9t5zAEow4kiTOGM2I81pqTMSwu+DAfEOey2JI2s8TEFt8PPWcPJEM0Lr6UbZUSB5gTIScNHkExOq7E4OoTmYoaX2cegpqA5F4hpKp18Grk9M0GZ3Ggk7i7jYpb6JYzkaghOzkLk3Qy3p1hX8QHCGal7NmIGeTIRUL6s0FdRPYzEDcFBv0z3uZXiOzLaj5esSLDJf5VDJBbMYumOw6ypsCm4pDCx/PKzRZPA2kqcdgcWwmbSLk7Pq9TTqtapA8g/FjJhY9ztkwBq9Mj9yk/3vAiYMJwInh5CRrxZ1XwVM+3TiIFphMBWTDYjSyrVcnIwh49osXZ/qgzstvLwYsAPvFiziEv+/1SSO4uIEsU+lfHr18ab36m5QXBRRQQAEFFFDATwj/B3tcJN4AUAAA

  values:
    ### For development purposes - set it to 0 (if you want to register extension but use local process with "make start").
    replicaCount: 1            

    ### For development purposes (tag) or for production use with internal registry (registry)
    ### possible to overwrite default values from charts/images.yaml. Works best togehter with "make TAG=mydevbranch build-images push-images"
    ### "image" overwrites extension (for seed) and "images" overwrite installation/agent (for shoot) images.
    # image:
    #   repository: localhost:5001/gardener-extension-cri-resmgr
    #   tag: mydevbranch
    #   pullPolicy: Always
    # imageVectorOverwrite: |
    #   images:
    #   - name: gardener-extension-cri-resmgr-installation
    #     tag: pawelbranch
    #     repository: localhost:5001/gardener-extension-cri-resmgr-installation
    #   - name: gardener-extension-cri-resmgr-agent
    #     tag: pawelbranch
    #     repository: localhost:5001/gardener-extension-cri-resmgr-agent
    
    ### For production or testing
    ### Default values are taken from 
    ### override defaults values from: charts/gardener-extensions-cri-resmgr/values.yaml and (internal) charts/gardener-extensions-cri-installation/values.yaml
    ### name should be one of: fallback/default/node.NODE/group.GROUP/force 
    # configs:
    #   fallback: |
    #     ... body ... - will be mounted to installation daemonset then copied to host and passed as --fallback-config to cri-resource-manager systemd unit
    #   default: |
    #     ... body ... - will be watched by node agent to push to all nodes (overwriting builtin and fallback)
    #   force: |
    #     ... body ... - will be mounted by installation daemonset then copied to host and passed as --force-config (overwriting builtin/fallback and config provided by agent)
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: cri-resmgr-extension
spec:
  deployment:
    deploymentRefs:
    - name: cri-resmgr-extension
  resources:
  - kind: Extension
    type: cri-resmgr-extension
    globallyEnabled: false
    reconcileTimeout: "60s"
