---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: cri-resmgr-extension
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+0ba3PaOjaf+RUacu9M2wnGPAw73tmZpYS27LZJhpB2+qkjbAHe2JZXkqHc9v73PZJsYx7hkbT0tuszmWCko6Oj89I5kplg5pKQsAr5LEjIPRpWHOZVGOHBhFXPvgmYAG3LUp8A65/qudZs1OqtVtMym2dmzWo26mfI+jbT74aYC8wQOmOUil14+/p/Upjs1H93ipkwFjjwnzKHVHCr2XxI/1L1oP+61a6ZjXatDvpvN6zGGTK/1SJ3wf+5/s9Rl0YL5k2mAtXNeh31Q0F8aGQRZViAPRio4/toIDE4GhBO2Iy4Rum8dI7eeg7YDHFRHLqEITElqBNhBz6Sngv0njBpVKhumOiZRCgnXeXnfwcKCxqjAC9QSAWKOQESHkdjzyeIfHZIJJAXIocGke/h0CFo7ompmiYhAmygjwkJOhIYsDHgR/BtnMdDWCiGJUyFiOxqdT6fG1gxa1A2qfoakVff9ru9q9teBRhWQ+5Cn3COGPlv7DFY6miBcAT8OHgEXPp4jihDeMII9Akq+Z0zT3jh5AJxOhZzzAhQcT0umDeKxYqwUu5gzXkEEBcOUblzi/q3ZfSyc9u/vQAaH/rDN9d3Q/ShMxh0rob93i26HqDu9dVlf9i/voJvr1Dn6iP6d//q8gIREBVMQz5HTPIPTHpSjEp16JaQFQbGVDPEI+J4Y8+BdYWTGE8ImtAZYSEsB0WEBR6XyuTAngtUfC/whLIRvrkoo1TCkZeo30azWinEAbHRMrosQ07JJRzaI6FQO+gN8QPkyNijRQouCiaYjKQxcwivBDgE/kD0HGV0JPbrJKChiNH/EEeUSmIRwbyJ0uQUpVnKlWnUQM3QlfFZrhm1lmGWSz/aMU8Eu+O/IGAzWIBbPGWO4/f/drNhFvv/KeBQ/UfMoxDXFo6POT8yI9i7/1sttf9bZtts1WpnZr1Rr1vF/n8KKPb/Yv8/xf7PQdBu7AMh4/5v3PBoFTKCey90bXSThJauDC2lgAjsYoHtEkI6Y9gZokoz7MeAVMu2ktLEpyPsX5Ixjn1hozH2OVnNMMrplEiFs2z5We6QzZTPV4xfMSk4NP5LtwfFYsehcXhkSbi//qsv47/ZkvG/ASVhEf9PAEX8L+L/ieo/He1vdSDp6EBydLjXWBwUB6hfviBjQHyCYbqrtBn9+Sdg+XhEfC6pIqkv4z4ewToIhDK59xwy04/2zNPAofH/05T4YAHcENHRZ4F74r/ZaKn834Q9vGG2ZfyXBWAR/08BX75UEHLJ2AshNHsBuHwZVZQHyR5vjKaY3zDo/4zKfIrrVssuI+O9TLrAkyS+IfAEZSOgTgzFGJV/5//8na9jMhJR7gnKFrtIgN+SbQTtRxMMXfkl9/ijpf7XgUP9n42w89iLgD3+32w1rGX+Z7Wl/9ebRf53EijyvyL/+175X6VSWckBVQzBsZhC7f2Htq31s4CuD/5I2ID6ZEtqmMUobqRxy3B8Grv2vqTx6eng9pHqbiLclovKbYbFYDt2qQIDvdeMxpHiQH6NODxklxm61SWRTxcBCUW+U+W1GkFOXQFSygUlR/B/lPRNiFCfPtiRephj4UzVU6SeHsXE/gk2yD6oo825HK3sR06E3cQcGZlI58kb1OZcQSwtNZzMyWhK6b1Dw7E3ifWgwxiQT3EEBkk084ykjw8I+AhJuCFnxKHMfaQsMnJ7Z9LXZm7Wujpf+UV5k3i5vEkmK8K+v5UsUde+VsH1RHy48qJ1NR60Um0pAY709JyA4kXCymzTTbZK0KGgWi/cbaEqdKxRS4zsaYH0JTSA5f8K8RRWMyBjOW0q4R3CAKzNTeWpS+fxSN4qq6i+9UDjWx5jnCD/OzT/z9ygogqsGciAsopMDmS6Q3aWBvvqf6ue3P/WoP63ZP0PVUCR/58Ekip/pXp+r5R7nepWWuLWo7yusol3ODr2FG+7DZ3wbC/lVfHBP62asY2+luTsu0TyFRJ9oC9Q8yc/WTjU/5d54fGnAPvqf6vRTN7/sFrtlgX+X7dqzcL/TwFF/V/U/6e4/5HV5jI7vcyiyV/4AkgKw1Z5+syTfW9ARZQt3spV28hUPcoQuGYk2S+Sxq7MBjUrHDiU24dmJpBlyNscd4/PoNPwnBDOSVJRDcGrtHrSpuxUf99+n6KDezj3PA6qj9jPlVS8EKp8l6Bn6hwf/WYME56Nl6C0Gwz+XD4ouSw/RwZsu/oOAjjKc5nbf3WDvyLep5QoqRFIiPIvqlwdSECqP18gHD4OpCIjGnhQykDlQA/RoGS5ooT0gsfIC0+13cS+f0PBbhcrtqwvU6Ksc13oR1gSCWdLfaQL6b/rvO6973WH14NP1+97gw+D/rCXYUEprF/uqap3gXN5WnVr4rZuD3k7pkEAQSvPwW6TzhBn1I8D8k6qjm8uQFsuz7EcSExp15LtZSaVIFYfK750wocy563Tr0sth8cIdq9DH9QtWEwe9iS9/A0LXF+3k5YCdm6OQyqBVUJHCeUwkTyas32SdvULZu+oC6SadTO3hJ+oFji+/k80dkQZsK/+b6n3f/X73/WGev+3XSvq/5PAmsclyv0OJf/S0U9d5Mslrq/vK+TqH8GA4SFMKvl6+sJA9QWCz3M1jkEeTNBvepjk8CL9ApIQ8vgX2f/YJj1NID8SWu1cUzY+ZSUblIvAL6rf+3Rht//P9Lqe+APAPf7fsKzs9x9W06zJ33+0asX7/yeBov4v6v/vVf/rAkTXyclrWrCV1A2PzzyILmQCAXNPZSmLXDyxkUpC5OVKlCtUOv4cL3ipVDo/P0f/AkeWYiOfMayTSAOY0jlaTyFlBukA2ojIHwjOPBfkLVef/MhQrUYPUlSTXxHoQkTpSb0q5yq7VOm1MaEIzOheCgtsgwQjIm/bkt6kUNHlyfkGN7pM/qosU2Pa6vmgQq+S5zkx7rywzpNEfyl7nzrYn1IubMs0a/tq+nXqhzEFiwjFt+dGky3lD1dsVAPVo+E1etlDd7e9S/nYHfQ6w570ilf91+86N0q5yx+IYp7m7VqlHAhIDL0nSwcekT9kJHIlKkZgYLJROgEDW0nx5BD5k1Q+hV2Bl5J9X5r6mFKpULnWscfAJH35ZqU+SiCA56qGkm6ggXQ5SHn0wHo2ktJKvTJmNKg4gvn67F31QIBA8ykW+s3MGUEBLMVTJNWwRkpCs5TWPFpxZRVd4Q8sH7y5nHQqlkeYaQrNy96rzt3bYUpIesEwGSdL9EH/spfJMNKnApJT9IDpaEfIZxKKrB6Z8tdxhDcDDgWFdjpZVLCKm7oz3XMG+ftyDd2bOxu1LTNQLTByQljae0lGMZhfesue/mD4wpEx/0LPf5H1ysMWRjVvbhxk1aJOeG0IJ2PbeHExhvBjP3vWVffyz78+G5AAbEM+xCH8v1MvFsDDLSQVQn3S6Plz48VPUQsWUEABBRRQQAEFFFBAAb82/A+cc2d+AFAAAA==
  ## Example values for development/testing puropses
  #values:
  #  replicaCount: 0            # for development purposes (if you want to start with "make start")
  #  image:
  #    repository: localhost:5001/gardener-extension-cri-resmgr
  #    tag: latest
  #    pullPolicy: Always
  #  imageVectorOverwrite: |
  #    images:
  #    - name: gardener-extension-cri-resmgr-installation
  #      tag: latest
  #      repository: localhost:5001/gardener-extension-cri-resmgr-installation
  configs:
    foo2: |
      foo-2-from-ctrldeploy
    foo3: |
      foo-3-from-ctrldeploy
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: cri-resmgr-extension
spec:
  deployment:
    deploymentRefs:
    - name: cri-resmgr-extension
  resources:
  - kind: Extension
    type: cri-resmgr-extension
    globallyEnabled: false
    reconcileTimeout: "60s"
