---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: cri-resmgr-extension
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+1abW/bNhDOZ/+Kg4sC2xDJL/LL4GHA3KRrjQVOYKct+mmgJVrmIosaSdnxgv73HSn5LU5tx0ndruPzIZFF8u54d7w7UgyJCGhMhUNvFY0l47HjC+YIKsehKJ08C8qIZr1u/iPu/zfPlVq13qyUvWaleVKu1Gte7QTqz8N+O1KpiAA4EZyrbf12tf9HEW61/9mICOXOyDh6Cg9t4Eat9jn7V2peZcX+VbR/06t7J1B+rkluw//c/i/gjCczwcKRgmq5WoVOrGiEL0XCBVHoDy60owh6uoeEHpVUTGjgFl4UXsAF89FnaABpHFABakShnRAf/+Utp/CeCu1UUHXL8IPuUMybij/+ghRmPIUxmUHMFaSSIgkmYcgiCvTWp4kCFoPPx0nESOxTmDI1MmxyIigGfMxJ8IEi2Jtg/wR/DVf7AVFGYI2RUkmrVJpOpy4xwrpchKUo6yhLF52z193+awcFNkPexRGVEgT9O2UCpzqYAUlQHp8MUMqITIELIKGg2Ka4lncqmGJxeAqSD9WUCIpUAiaVYINUrSlrLh3OebUDqovEUGz3odMvwqt2v9M/RRofOtdvL99dw4d2r9fuXnde9+GyB2eX3fPOdeeyi79+h3b3I/zR6Z6fAkVVIRt6mwgtPwrJtBqN6aBP6ZoAQ54JJBPqsyHzcV5xmJKQQsgnVMQ4HUioGDOpjSlRvACpRGzMlPERuTkpt1AgCcvN34JJpRCTMW3BMrosQ04hoBLfJ8p0bcNbGo3B17EnUykuUXTBfCRPhU+lMyYxyoeql7Cgo3u/yQMaJIL/RX1VKKhZgnxzo2kWhclcqrJbQTNj00LOYsWtNNxysfC1F+aRsD3+K4o+QxQui6fweET+rzSbOv83a17D5v9jYF/7BzSJ+GxM4wPKgR35v9qoesb+9XKz3Kg2TjAN1csVm/+PAZv/bf4/Rv5HnckSFgE3LA5acL6IJoUxVSQgirQKAFmFsDUk5b0kWg673t2B26MRJcivO38Nnz5hr4gMaCQ1VdDM3Zt0gBOhGMtcxkv7cNLK0OMFnTDd9hZNxMXsQs8aSwfTYhxBZoK8J1GK1POXZzyNVSaKRAl9HJoJMybKH12sSHeofADz8JwTXtGkRrTG43AuAHNNaCSCcXTw2VlEpOzuSUDrQEzQMdq+r/Wy/zifx3pZoxvNBXD2dJMMbIxebOzDYj9KAwxA5lUR3Mw4K92u0ii64mi82ZpBTZubLBpXx2FswkI0WCrZgdJ+gjngOOi4ge6n3QO7/TokkaTHrTz3zf9zs/va7I8sAXbu/+uNZf6vVDD/e1gB2Px/DNj8b/P/MfK/REUHaYSE3JufTfJZFANXqxnl0fXARAfpFlQWW8lCGPEBic7pkKQRJuosqK6dMBTnLMGEs8X0F2cHC06r5xXu93gosG/8z/M3yfL34xLA7vPf6jL+l/X+z/M8u/87Cmz8t/H/SOe/WbTvr20EvuHt39demcfBvvH/zxGN0AOkq5JHfwvcEf/LXsPU/2XM4V65qeO/PgC28f8YuLtzAAI6xC32YmfsmBWkW9gQRkReCWy/haIckWq90Sre2xkrEsJiBO4TYzWE4kv520t5v6egCZdMH6JsI4Hrlj5EsHUwwTjQP1Yev7bWvx3su/7FgPiHXgTYsf5rDa++rP/qTb3+qzVb/x0Ftv6z9d+Xqv8cx1mrAU0MIaka4d77n8y37p8FnEW4Hqno8Yg+UBouYpR053HL9SOeBq1dRePTy8GHR5q7CfFDtahOMyJF32kVHBzI3gieJkYCx3wMMZ8P8ssM2dvlJ9bVRlPXZh00awdJmSWoJcK/g7wtpMr8j9CPzMNUf2YwT4l5OkiI3Qw2yH7WRpu8/MzYBzIiQe6OgoZ68aw61Cavcao9NQ6ndDDi/Mbn8ZCFaTZoPwH0U5qgQ9JMeEHnj59R8CM0EcRSUJ+L4EBdLMjt5JRdmwkWb9f5FX8qbhIvFjfJLDZhX95Lll3v/Szh0lPp/sZL7ptxr5lmnjImScZeUjS8ykWZbC6TBzXoczQti7d7qAkd96jlTva0QPoKX6Dnfw/xFGfTo0PNdq7hLcrAXptJ5alTl+lA3yozUf3BA43nPMY4Qv23vf6fZHuqJ14A3nX+65WX93+8ZkXf/9KfAW39fwTY+t/W/1+q/s/uXmT3ZPJjmhZMqi6TE4bRhYYumnbndQlFwhaYQwgdXJOVOxrtaEpm0h7mWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWGj8C/wd95oAUAAA
  # values:
  #   image:
  #     repository: v2.isvimgreg.com/gardener-extension-cri-resmgr
  #     tag: latest
  #     pullPolicy: Always
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: cri-resmgr-extension
spec:
  deployment:
    deploymentRefs:
    - name: cri-resmgr-extension
  resources:
  - kind: Extension
    type: cri-resmgr-extension
    globallyEnabled: false
