---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: cri-resmgr-extension
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+1bX5MjNxGfUOHFuQAFhIc8UI23UgVkZ2yP/10ZqIpvd3Pn4rJ75d27qzwReUa2hx2PBkljn7MEHvIV4InKA1XANwE+B8UbbxRfgJZm7PV692yv7fMmF/2q5BmPNOqWutXd0kg9wn0aUW7TF5JGImCR7fHA5lQMerxgbQVFRL1a1VfE/FXflyrlYq1Sr1YqFatYwkvRgup2yC9GIiThABZnTC4qtyz/K4reQvkf9AmXzpgMwk1oKAHXlFxvlj+KvoTyd6v1UrFcL7ko/3q5WraguK1GLsLXXP57cMDiMQ96fQlu0XWhFUka4kMeM04k6oMDzTCEtiohoE0F5UPqO7m93B48DjzUGepDEvmUg+xTaMbEw0uWsw/PKFdKBa5ThB+rAvksK/+Tn2ENY5bAgIwhYhISQbGKQEA3CCnQFx6NJQQReGwQhwGJPAqjQPY1mawSZAM+zqpgHUmwNMHyMf7rzpYDIjXDCn0p40ahMBqNHKKZdRjvFcK0oCg8bh0cHZ8e2ciwfuVpFFIhgNPfJAHHpnbGQGLkxyMd5DIkI2AcSI9TzJNM8TvigQyi3j4I1pUjwinW4gdC8qCTyCudNeEO2zxbALuLRJBvnkLrNA8Pmqet032s43nr7NHJ0zN43my3m8dnraNTOGnDwcnxYeusdXKM/z6E5vHH8MvW8eE+UOwqJENfxFzxj0wGqhu16OCU0isMdFnKkIipF3QDD9sV9RLSo9BjQ8ojbA7ElA8CoYQpkD0fawmDQSC1jojrjXJyORIHmfgbMCzlIjKgDbi0LpcmJ+dTgc9jqYs24RENB+Ap25N2KQ5RVMHsTZZwjwp7QCLkD7tewLQeVfphZtAg5uzX1JO5nBzHSDcTmiKRG064KjolFDNmTfnMl5xSzSnmc3c9MHeExfZfUtQZInFYbEJjVf9frlVrVbem7H+lXDX+fxdYVf4+jUM2HtBojXBgif93q7VSFv+VKpUa+n/XrdTrxv/vAsb/G/+/C/+PfSYKGAScB5HfgMOpNckNqCQ+kaSRA0gjhIUmKSslUHJY9OICnDYNKUF6x5PH8NlnWCokHRoKVSso4s550sGGULRlTsAKq1BSnaHe53QYqLxHKCLGx49VqzF00DlaEUTKyDMSJlh79vCAJZFMWRHIoYevpswMiPT6j2e4W5c/gIl5ziqe6UmF8AqN9akATHpCIeYBQwUfH4REiOMVK1B9wIeoGE3PU/2y+nsei9SwRjWaMGCvqCYpggFqsZZPEHlh4qMB0o/y4KTCmSn2JAnDJwyFN74iUJ3nxNPM2ffQNmEg6l92sg2FxYzdtcGfw6r+fyJ2T4n9liHA0vl/tabn/9VivVgrldD/l123avz/LmD8v/H/u/D/AjvaT0KsyDm/r53PNBh4MutRbh0PDJWRbkBpOpXM9ULWIeEh7ZIkREfdJaGgV1cY8hOSoM3ZtPnTtYMppdn1Cud1XBRY1f5n/puk/vt2DmD5+q97af+LNWX/y+WSsf+7gLH/xv7vaP03tfanVyYCX+Lp312PzN1gVfv/qz4NUQOEI+NbfwtcYv+L5ZqO/4vow8vFurL/agHY2P9d4OLCBvBpF6fY05mxrUeQygm60CfiCcf8F5AXfeJWa4383MxYkh5M38B5YiS7kH9PfPCemC/JacxEoBZRFlWB45beVGFj7QojX/2Zub3rXv/yYNXxzzvEW3cjwJLxX6mVq5fxX7Wuxr9bMfHfTmDiPxP/var4z7btKzGgtiEkkX2ce3+a6tb8WsBBiOOR8jYL6Q2h4dRGCWditxwvZInfWBY0bh4O3vym3psQ3RSLKjfDE9SdRs7GF4OHnCWx5sDWH0P054NsM0P69PIT62ymjmvTAoq0jVXpIag4wt9OltejUl9D1CN9M1KfGfRdrO/WYmI5gWvVvlRG12l5qbDXJET8TB057anBM6tQ12kNEqWpUW9EO33Gzj0WdYNekr60GgPqLolRIWnKPKeT25d08C16wo8Epx7j/pp9Ma1uKaV024w/fXqVXv6n+euV5/PXq5lOwl69llwWnftbwKEnk9WFF8+LcaWWppoyIHFKXlAUvMxYGV4fJjf2oMdQtEG0WEO16ZirLVOyzQzpA3yAmv862FNsTZt2FdlJDy/oDCx13als2nSRdNSuMm3Vb1zQ2OYyxg7iv8Xx/zCdU224AXjZ+q/65jfZ/11zq2r/V8018/+dwMT/Jv5/VfF/uvci3SeTLdM0YOg6gRgGaF1oz0HRLtkuASBJrwF6EUIZ13hmj0YzHJGxyOVmd9w0oJRD1s5O4MERPD09OlS3B+2j5tmR6qoPWw8/aj7R7b3cNUyEWgFTXwshNXhYgSqRun4l1Q79VKmnr4oSDCnG6qHqGR74dFJOvaL2KQsMMDEsSJ9qH9llrAG/TbfSsAG18b/d5Wxgd9Dk23qj810tSS22/86MA3DEKF6PxmL7X57u/03tv1r/LVaLFWP/d4FO8VnrI7jvuOrPdyzrjxfven9+85tvvv/5Oys3OWI+LdeWl/udqrAwYvx88aAv6BEhlhTaTmxiYPC1QCK79v23rbJb0mZ1L/8j+N53n941VwYGBgYGBgYGBgYGO4SM37B+j9dvZP/fza5vzF0NDAwMDAwMDAwMDAwMDAy+uiC+Zf3vLcsa3bP09//J/P+f37asv2P6HNMHmH6A6fuY/v0ty/oXpj9heo7pHqZ/vG1Zf8X0F0xfYPoEUxvTLzD9HNM+pvcx/Qdp/A3TF5j+cC+l+QmmR5hsTD/EdA/Tf9+6yx4xMDAwMDAwMDAweD0Al/DipKF+BJWNol0rWzdnzT251buzWTc+f9lWeGuyYd6abKG3trAf39r0UIBlzZ0zUB16/TiCdeXEgrXJ4QcrPUChDuksPmphbeVEh7W9IybWFk68WFs5e2PtWbc99qNfWfFUkbX5ESZr43NUmuH1jnHdtUkyMDAwMDAwMDAwMDAwMDAwMHjF+D8EfXY9AHgAAA==
  ### for development purposes
  values:
    replicaCount: 0
  #  image:
  #    repository: v2.isvimgreg.com/gardener-extension-cri-resmgr
  #    tag: latest
  #    pullPolicy: Always
  #  configs:
  #    foo2: |
  #      foo-2-from-ctrldeploy
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: cri-resmgr-extension
spec:
  deployment:
    deploymentRefs:
    - name: cri-resmgr-extension
  resources:
  - kind: Extension
    type: cri-resmgr-extension
    globallyEnabled: false
    reconcileTimeout: "60s"
