---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: cri-resmgr-extension
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+1b63PaSBL3Z/0VXfi2avcqCCFeV9yXIw6bcBc/CjtO7afUIA2gs6TRzozAbLL/+/XMSFiADfgRkuypP9h6tHp6+jW/HokJ4T6NKa/SW0ljEbC46vGgyqmIJrx29CLkIHVaLf0faf2/Pq43G3W37jScVvvIqbearnMErZcZfjulQhIOcMQZk9v4dt3/QWmy1f8nU8KlvSBR+JwxlIPbzeZD/leuR/+7rQ76v1N30f+dRqtxBM5LTXIb/Z/7/xhOWLLgwWQqwXVcFwaxpCFe5AnjRGI82NALQxgqDgFDKiifUd+2jq1jeB94GDPUhzT2KQc5pdBLiIf/sjuv4JpyFVTg2g78rBgq2a3KL/9ECQuWQkQWEDMJqaAoIhAwDkIK9NajiYQgBo9FSRiQ2KMwD+RUD5MJQTXgt0wEG0mC3AT5EzwbF/mASK2woqmUSbdWm8/nNtHK2oxPaqFhFLX3g5P+2WW/igrrRz7EIRUCOP09DThOdbQAkqA+HhmhliGZA+NAJpziPcmUvnMeyCCevALBxnJOOEUpfiAkD0apXDFWrh3OuciA5iIxVHqXMLiswOve5eDyFcr4OLh6d/7hCj72hsPe2dWgfwnnQzg5P3szuBqcn+HZr9A7+w3+Mzh78woomgqHobcJV/qjkoEyo3YdXFK6osCYGYVEQr1gHHg4r3iSkgmFCZtRHuN0IKE8CoRypkD1fJQSBlEgdYyIzUnZlkWSIHN/F2Z1KyYR7cJddbkrOZZPBV5PpGbtwTsaRuCp2mNMiimKIZg9yVLuUVGNSIz6oekFLOUo7rdZQYOEs/9ST1qWXCQ4buY0NYQ1y7Vy7Dq6GW8t9azU7XrbdirWt07MA9H2+i8pxgyRmBbPGWP/9b/eqHfU+t9pum65/h+C9vV/wgOGdW3hhUSIRyKCnes/Yj61/recjtOu148ct+G6rXL9PwSV63+5/h9i/RdoaD8NUZB98w9hB6yGiOAmiP0uXGSl5USVFiuikvhEkq4FYBDD1hJlzUiYIlN9uZRYk5CNSPiGjkkayi6MSSjoKsKo5EOCLmfL6S+xw3KkIl6x/4qgYN/6r9IeHUs8j6XxI1vC3f2fe1f/nbaq/w1sCcv6fwAq639Z/w/U/5lqf2kKSc8UkkeXe8Ml0HHI+vkz2EMaUoLDneWX4c8/kSskIxoKJRWUv+ybdITzoFjK1Nqzz0jfOjMPQ/vW/09TGmIECFsmj94L3FH/nUZb438H1/CGo/o/FxvAcv/vIPT5cxXAp+MgxtIcRJjyFajqDFJ3gjFMibjgeP8WKmJK3Fa7WwH7WoEuzCTFb0sygeUT2CfGcgyVn8S/fhLrnJwmTASS8cU2EZi39D6B3ScLjH11Ujj81lb/fmjf/Ocj4j31RcCO/G+2G607/NfqqPx3myX+OwiV+K/Ef18L/1Wr1RUMqGsISeUUe+8/TGyt7wWchJiPlA9ZSO+BhssaJey8btleyFK/uws0Ph8O3v+kfjcR34dF1TLDU4ydrlXFB4O3nKWJ1kCdJgIPli8zzFWfJiFbRDSWxZsa1xoGNXQVRekUVBrh31F2b0Kl/h9iHOmDOZHeVB8l+uhJSuweYEPsgz7aHMszzn7iQMTPwpHTiUqeYkBtjhWlKlLjyZyOpozdeCweB5PUPLSfAuooTTAgqVGe0/zwAQM/whJ+LDj1GPefaIuluJ0jmddm/vLq6niVv1c2hVcqm2KWTdjXj5I71rXTGqaeTPd3XrLuxr1maiIlIokZXlB0vMxUmW2myb0W9Bi6Noi3R6guHWvSsiB7XiF9jRcw8v8K9RRnM6RjNWxu4S3GQK7NReW5UxfpSL1V1lX93g2Nl9zGOAD+2xf/L9OgqhusGdqA8aoCBwru0K2twa7+v+Wuff/lYhdQ4v+DUNblr3TP19q557lvVSTeu5V3omPilCSP3cW7P4YOuLeX66r1EJ9Ww7gLXyw1+jaTfEGgj/IlNH/wnYV98/8OFz5+F2BX/+92Gnn+N52Gi/nvNtvl/t9BqOz/y/7/EO9/VLd5h07fLKvJd/wCSBmjq3H6LFD33qGLGF+8V7PugqPv6EAQRpFsvcgunig0aFQRqKFaPowykWpD3he0ezqCzstzJrhgSS01xqwy7skvLXf1d633OTumh3cj0qj2hPVcWyWIscv3Kfys9/Hhb/ZVprP9Gp12QTCfK3uBy8ovYOOya95BoEZFLQvrr7kQrpj3OS1KHgSKkuKHKmd7ClDuLzYI+z+HVlEVDTMoV6C6Z4YY0rZccUL+gscuGk9fu0jD8IJh3C5WYtm8TEmWN9eN/ohIovHszh/5RAanvbf96/7J1fnw0/l1f/hxOLjqL7mwFTYf99T0t8AFnFa7F7itx0MxjlkUYdEqarA9pJ86zRkL04ieKk+Lzfk+hHtzitRzKinum3OBj1Pin8chOkvylD6cB49S3qi+EWzbdfbyHqBbUO85LUBOvvl+65T5KKrpOoUZ/aBQ+7uk7fh/ZuLmmT8A2oH/sZ43Df5vO3Wn3lHff7frbon/D0El/i/x/9fC/waAGJycfabRhZlrB2IWYHWhExtdu3MZlmTSBb0JoTZXkwJQ6YVzshCWZR0fH8O/MZGV2egtwXlSFQBTNof1JU+teB6yjaj6gdAs8NHeavbZj4z0bMxDWmr2FbEBItpP+lMZX8elXqDtCQMMoxtlLIwNGo2o2m3P7mZAxcCT4w1tDEz+oiPTcHb18V5Ar1rUOQvuorGOM6hwZ/uQeSScMiG7Lcep78L069L3UwonEcuX18aItYrNVRfq6Hq4OofXffhw2X+jDk+G/d5VX2XFr4O3p70L7dy7H4gRkQML41KBAhSHgTEqgUf0D1WJfMVKAANMXVRJwDFWcj71iPpJmpjiqiAsc1UjpzFjyqFqroJFtIrn1TFnUXWE7U5VB0UJXEoqqaSSSiqppJJKKqmkkkoqqaSSSjoY/Q/SC1rzAFAAAA==
  ## Example values for development/testing puropses
  values:
   # replicaCount: 0            # for development purposes (if you want to start with "make start")
   image:
     repository: localhost:5001/gardener-extension-cri-resmgr
     tag: pawelbranch
     pullPolicy: Always
   imageVectorOverwrite: |
     images:
     - name: gardener-extension-cri-resmgr-installation
       tag: pawelbranch
       repository: localhost:5001/gardener-extension-cri-resmgr-installation
  #  configs:
  #    foo2: |
  #      foo-2-from-ctrldeploy
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: cri-resmgr-extension
spec:
  deployment:
    deploymentRefs:
    - name: cri-resmgr-extension
  resources:
  - kind: Extension
    type: cri-resmgr-extension
    globallyEnabled: false
    reconcileTimeout: "60s"
