---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: cri-resmgr-extension
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+0ba2/bODKf/SsIZxdoi1iW5ddBhwPOddzWd20S2E6LfipoibZ1kUQdSdn1tvvfb0hKsuw4fiSpu7unQVErfAyH8+LMiJpi5pKQsAr5KkjIPRpWHOZVGOHBlFXPngVMgHazqX4BNn/Vc61Rr1mtVqNpNs7MWrNRt85Q83mW3w0xF5ghdMYoFbvG7ev/k8J0p/y7M8yEscSB/5Q1pIBbjcZD8peiB/lbzXbNrLdrFsi/XW/Wz5D5XJvcBf/n8j9HXRotmTedCWSZloX6oSA+NLKIMixAHwzU8X00kCM4GhBO2Jy4Rum8dI7eew7oDHFRHLqEITEjqBNhB36Sngv0kTCpVMgyTPRCDignXeWXfwcMSxqjAC9RSAWKOQEUHkcTzyeIfHVIJJAXIocGke/h0CFo4YmZWiZBAmSgzwkKOhYYRmMYH8Ffk/w4hIUiWMJMiMiuVheLhYEVsQZl06qvB/Lq+363dzXsVYBgNeU29AnniJH/xh6DrY6XCEdAj4PHQKWPF4gyhKeMQJ+gkt4F84QXTi8QpxOxwIwAFtfjgnnjWKwxK6UO9pwfAOzCISp3hqg/LKPXnWF/eAE4PvVH765vR+hTZzDoXI36vSG6HqDu9dVlf9S/voK/3qDO1Wf07/7V5QUiwCpYhnyNmKQfiPQkG5Xo0JCQNQImVBPEI+J4E8+BfYXTGE8JmtI5YSFsB0WEBR6XwuRAngtYfC/whNIRfn9TRqmEIy8Rv43mtVKIA2KjlXdZuZySSzi0R0IN7aB3xA+QI32PZimYKKhgMpPGzCG8EuAQ6APWc5ThkaPfJg4NRYz+hziiVBLLCNZNhCaXKM1TqkyjBmKGrozOcs2otQyzXPrZhnki2O3/BQGdwQLM4ilrHH/+txt1szj/TwGHyj9iHgW/tnR8zPmREcHe87/ZUud/02ybrVrtzLTqltUszv9TQHH+F+f/Kc5/Dox2Yx8QGXd/44ZHqxAR3Hmha6ObxLV0pWspBURgFwtslxDSEcNOF1WaYz+GQbXsKClNfTrG/iWZ4NgXNppgn5P1CKOcLomUO8u2n8UO2Ur5eMX4KwYFh/p/afYgWOw4NA6PTAn353/Wyv+bLen/65ASFv7/BFD4/8L/nyj/095+qB1JRzuSo929HsVBcDD02zdkDIhPMCx3lTaj33+HUT4eE59LrEjKy7iLx7APAq5Mnj2HrPSzLfM0cKj//zIjPmgAN0R0dC1wj/836y0V/5twhtfNtvT/MgEs/P8p4Nu3CkIumXghuGYvAJMvo4qyINnjTdAM8xsG/V9Rmc+w1WzZZWR8lEEXWJIcbwg8RdkMyBNDMUHlX/k/f+WbIxmJKPcEZctdKMBuyTaE9qMRhq78I/f4s7n+x4FD7Z+NsfPYFwF77L/RqjdX8V+zLe3fahTx30mgiP+K+O9HxX+VSmUtBlQ+BMdiBrn3b1q3NmsBXR/skbAB9cmW0DDzUdxI/Zbh+DR27X1B49PDwe0z1buJcFssKo8ZFoPu2KUKTPTeMhpHigL5Z8ThIXuZoVtdEvl0GZBQ5DtVXKsHyKUrgEqZoKQI/h8nfVMi1K8PeqQeFlg4M/UUqadHEbF/gXtoH5TR/bUcLexHLoTdRB0ZmUrjySvU/bWCWGpqOF2Q8YzSO4eGE28a60mHESCf4ggUkmjiGUkfH2DwEZxwQ86IQ5n7SF5k6PaupF+buVnr+nrlV+X7yMvl+2iyJOzHa8lq6MafVTA9ER8uvGhTjAftVGtKgCO9PCcgeJGQMr9vJls56FAQrRfu1lDlOjawJUr2NEf6GhpA8/8K/hR2MyATuWzK4R3MgFH3D5Wnbp3HY/lWWXn1rQWN5yxjnCD+OzT+z8ygohKsOfCAsooMDmS4Q3amBvvy/6aVvP+tQf7flPk/ZAFF/H8SSLL8tez5oxLudSpbqYlbS3ldpRMfcHRsFW+7Dp2wtpfSqujgX9bV2EbfS3L1XSz5DoE+4Beo8SevLBxq/6u48PgqwB77h7S/ru2/bTYaVh3s32q0G4X9nwKK/L/I/0/x/kdmm6vo9DLzJn/gF0CSGbaK0+ee7HsHIqJs+V7u2kam6lGKwDUhyXmRNHZlNKhJ4UChPD40MYFMQ97nqHt8BJ265wRxjpMKawhWpcWTNmVV/X3nfToczMO543FQfcR5rrjihZDluwS9UHV89IsxSmg2XoPQbjDYc/mg4LL8Ehlw7Op3EEBRnsrc+asb/DX2PiVFSZVAQpS/qHJ1IAIp/nyCcPg84Ir0aGBBKQGVAy1Eg+LlmhDSFzxGnnmq7Sb2/RsKertc02X9MiXKOvPzSDh/tFqlG+l/6Lztfex1R9eDL9cfe4NPg/6ol42CVFhf7qmqu8C5OK26NXDb1IcNDcnRpxWObyMJ/Omb/tvhbnJWmp9g2rE0HF8B+Es7t9Jua8oGzqkfB+SD1JqHLXjHVjZpAxchcUmjO3YTj5TvQ3H+Vno2ZZwbxwh2r0MflFOwmDxs95pjGbP2seohRjlpYmPnaDgkr1lHdI+8o7h4GA8fTeo+0bj6/twH6gKqhmXe39PPDl0LeAY4vv6T6PgRaeC++k9L3f/W9/+turr/3a4V9Z+TwMMu8plLPivXeOoij9zi5v6+Q672GRQYHsKkkmOlF0aqrxD8nqt5DPIggn7R0ySFF+kfwAkhy//I/sf2A0YiyM+EVjvXlM1PSckm5Q6NV9UfXV3abf9zva8nfgC6x/7rzWb2/U+zYdbk9z+tWvH9x0mgqP8U9Z8fVf/RCaiukyTX9OAosQyPzz3wLmQKDnNPZUEWOfDURioIkS/Xolyi2vEXeMlLpdL5+Tn6FxiyZBv5imGfRCrAjC7QZowtQ2wHho2J/EB07rnAb7n75CNTtRs9SWFNviLRmZ+Sk7oq6Sq9VAmLMaUI1OhOMgt0gwRjIt+2Jr1JoqrT0/N71OgyyXelmXqkrZ4PSvQreZoT5c4z6zxJnVa896mD/Rnlwm6aZm1fTWcT+2FEwSZC8fzUaLSlfHHNRjUQPRpdo9c9dDvsXcrH7qDXGfWSLP5D50YJd/WBMOZpYqNFygGBHKHPZGnAY/Kb9ESuHIoRKJhslEbAQFfScXKK/CSZz+BU4KXk3JeqPqFUClTudeIxUElf3qzVpSQC41zVUNINNJAmByGPnmhlMymtWJUJo0HFEczX715UDzgItJhhoW/mzgkKYCueQqmm1VMUmqQ0KdSCKyvvCv9A88Gay0mnInmMmcbQuOy96dy+H6WIpBWMknmyJjLoX/YyHka6KiQpRQ+ojjaEfCSh0OqZKX0dR3hzoFBQaKfTZQUrv6k70zNnkL8voaF7c2ujdtMMVAvMnBKW9l6ScQzql96ySD8Yv3Ckz7/Q619kvbLYxqimzY2DLJ3WAa8N7mRiG68uJuB+7BcvuupexsvvLwYkAN2QD3EI/9+qiyXwMISgQqhfGr18abwqkuUCCiiggAIKKKCAAv4Q8D9VdDMRAFAAAA==
  ## Example values for development/testing puropses
  values:
    #replicaCount: 0            # for development purposes (if you want to start with "make start")
    image:
      repository: localhost:5001/gardener-extension-cri-resmgr
      tag: pawelbranch
      pullPolicy: Always
    imageVectorOverwrite: |
      images:
      - name: gardener-extension-cri-resmgr-installation
        tag: pawelbranch
        repository: localhost:5001/gardener-extension-cri-resmgr-installation
    configs:
      foo2: |
        foo-2-from-ctrldeploy
      foo3: |
        foo-3-from-ctrldeploy
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: cri-resmgr-extension
spec:
  deployment:
    deploymentRefs:
    - name: cri-resmgr-extension
  resources:
  - kind: Extension
    type: cri-resmgr-extension
    globallyEnabled: false
    reconcileTimeout: "60s"
