---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: cri-resmgr-extension
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+1a3XPbNgzPs/4KnHu723aVLMlfO+9lbpK1vnVJzk6329OOlmiZqyRqJGXX6/a/D6Rkx05S20ladx/8PSSySAIgAAIgxYSImOZUuPSdorlkPHcjwVxBZZaI5slHgY/odTrmP+L2f/MctFuB73c7naB94geddtg+gc7HYb8bpVREAJwIztWufvva/6VIdtr/dEaE8pYkS5/CQxu4225/yP7a9Gj/sNML/FYvCNH+vVandQL+x5rkLvzP7f8MTnmxFCyZKQj9MIRhrmiKL0XBBVHoDx4M0hRGuoeEEZVUzGnsOc+cZ/CaRegzNIYyj6kANaMwKEiE/+qW5/ATFdqpIPR8+FJ3aNRNja++RQpLXkJGlpBzBaWkSIJJmLKUAn0X0UIByyHiWZEykkcUFkzNDJuaCIoBv9Qk+EQR7E2wf4G/ppv9gCgjsMZMqaLfbC4WC48YYT0ukmZadZTN18PT84vxuYsCmyFv8pRKCYL+XjKBU50sgRQoT0QmKGVKFsAFkERQbFNcy7sQTLE8eQ6ST9WCCIpUYiaVYJNSbSlrJR3OebMDqovk0BiMYThuwIvBeDh+jjR+Hl6/unxzDT8PRqPBxfXwfAyXIzi9vDgbXg8vL/DX9zC4+AV+GF6cPQeKqkI29F0htPwoJNNqNKaDMaVbAkx5JZAsaMSmLMJ55UlJEgoJn1OR43SgoCJjUhtTongxUklZxpTxEXl3Up7jkILV5u/DPHByktE+3ESXm5DjxFTi+0KZrgN4RdMMIh17KpXiEkUXrEfyUkRUuhnJUT5UvYQ1Hd37ZR3QoBD8Nxopx1HLAvnWRtMsnPlKKt8L0MzYtJazEXhB1/MbzudemEfC7vivKPoMUbgsnsLjQfnfD3T8bwddm/+PgUPtH9Mi5cuM5o8oB/bk/7DT1fm/hX2CdruL+T8M272ezf/HgM3/Nv8fI/+jzmQTi4C3LI/7cLaOJk5GFYmJIn0HoKoQdoakupdEy2HX9+/BG9GUEuR3sXoNf/2FvVIyoanUVEEz996WE5wIxVjmMd48hJNWhh4v6JzptldoIi6Wr/WssXQwLcYRZCXITyQtkXr98pSXuapEkShhhEMrYTKiotnrDekeKx/AKjzXhDc0qZFu8Xg8F4CVJjQKwTg6+PI0JVJeHEhA60DM0TEGUaT1cvi4iOd6WaMbrQRwD3STCixDLzb2YXmUljEGIPOqAV5lnI1uV2WaXnE03nLLoKbNK9aNm+MwNmEhGt8o2YXmbsE+d8C/hUPz/8rskTb7A0uAvfv/Ttfs/zt+z+8GWP+FrTDs2Px/DNj8b/P/MfK/REXHZYqEvLffmOSzLgauNjPKg+uBuQ7SfQjWW0knSfmEpGd0SsoUE/WUpJJunzA0VizBhLP19NdnB2tOm+cV3n/xUODQ+F/nb1Ll74clgP3nv+FN/Pe7Ov63WoGN/8eAjf82/h/p/LeK9uOtjcA/ePv3uVfmcXBo/P91RlP0AOmp4sHfAvfEf7/VNfW/jzm85fd0/A96bfv97yh4/94FiOkUt9jrnbFrVpBuYVOYEXklsP0dNOSMhJ1uv3FrZ6xIAusRuE/M1RQaX8jvvpC3ewpacMn0IcouErhu6X0E+48mmMf6x8bj59b6PweHrn8xIdFjLwLsWf/tbqtzU/91enr9h21b/x0Ftv6z9d+nqv9c192qAU0MIaWa4d77j8q3bp8FnKa4HqkY8ZTeUxquY5T0VnHLi1Jexv19RePTy8H7R5q7Cfl9tahOM6JE3+k7Lg5kLwUvCyOBaz6GmM8H9WWG6u3NJ9bNRlPXVh00axdJmSWoJcK/k7otocr8T9GPzMNCf2YwT4V5epQQ+xncIftBG93lFVXGfiQjEtfuKGiiF8+mQ93llZXaU/NkQSczzt9GPJ+ypKwGHSaAfioLdEhaCS/o6vEDCn6AJuJcChpxET9SF2tyezlV12bi9dttfo2vG3eJNxp3yaw3YZ/eS2663vrZxKWnysONV9w240EzrTwlI0XFXlI0vKpFmd9dJvdqMOJoWpbv9lATOm5Rq53saYH0Bb5Az/8vxFOczYhONduVhncoA3vdTSpPnbosJ/pWmYnq9x5ofMxjjCPUf7vr/3m1p3riBeB957/6m9/2/e+ePga29f8RYOt/W/9/qvq/untR3ZOpj2n6MA89JucMowtNPDTtnusSAIokfTCHEDq4Fht3NAbpgiyl42zeuOlD4KBo15fw4hzejM/P9OPp6Hxwfa5V9f3w5Y+DKzPfm1vDROoTMP21EKqAhwR0jyr1a6tO6B/aPWPdlWBJsdQvtWYEi+mqnx6i7ylLLDCxLKjemhw55bwPf1ZXaXhGXfztTgXP3AmGfNdcdLZHUhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFk/F3xiCKl8AUAAA
  ### for development purposes (if you want to starte with "make start"
  values:
    replicaCount: 0
  #  image:
  #    repository: localhost:5001/gardener-extension-cri-resmgr
  #    tag: latest
  #    pullPolicy: Always
  #  configs:
  #    foo2: |
  #      foo-2-from-ctrldeploy
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: cri-resmgr-extension
spec:
  deployment:
    deploymentRefs:
    - name: cri-resmgr-extension
  resources:
  - kind: Extension
    type: cri-resmgr-extension
    globallyEnabled: false
    reconcileTimeout: "60s"
