---
apiVersion: v1
kind: Namespace
metadata:
    name: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ngnix
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx-sts
  serviceName: nginx-sts
  template:
    metadata:
      labels:
        app: nginx-sts
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: nginx
          image: nginx
          resources:
            requests:
              cpu: "2"
