# Copyright (C) 2022 Intel Corporation
# SPDX-License-Identifier: MIT License

trainer:
  max_steps: 5
  accelerator: "gpu"
  devices: 1
  logger:
    - class_path: pytorch_lightning.loggers.CSVLogger
      init_args:
        save_dir: "matsciml-logs"
        name: "training-logs"
    - class_path: YEET
      init_args:
        myarg: "hereeree"
seed_everything: 6
