name: "Validate Gradle Wrapper"
on: [push, pull_request]

jobs:
  validation:
    name: "validation/gradlew"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # pin@1.1.0
