name: Run pre-commit workflow
on:
  pull_request:
    branches:
      - main
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: file_changes
        name: Determine changed files in PR
        uses: trilom/file-changes-action@v1.2.4
        with:
          prNumber: ${{ github.event.number }}
          output: ' '
      - uses: actions/setup-python@v5
        name: Install Python 3.10
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -U pip setuptools
      - uses: pre-commit/action@v3.0.1
        name: Configure and run pre-commit
