name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - run: git log
      - run: git diff origin/master HEAD
      - uses: actions/checkout@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v2
        if: ${{ github.event_name == 'push' }}
        with:
          fetch-depth: 0
      - name: Determine next version
        uses: paulhatch/semantic-version@v3.1.1
        id: semver
        if: ${{ github.event_name == 'push' }}
        with:
          branch: "master"
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}"
      - name: Get branch
        id: getbranch
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "##[set-output name=branch;]${GITHUB_HEAD_REF#refs/heads/}"
          echo "##[set-output name=safebranch;]$(echo -n "${GITHUB_HEAD_REF#refs/heads/}" | tr -c '[:alnum:]-' '-' | tr A-Z a-z)"
      - name: Determine next version (PR)
        uses: paulhatch/semantic-version@v3.1.1
        id: semverpr
        if: ${{ github.event_name == 'pull_request' }}
        with:
          branch: ${{ steps.getbranch.outputs.branch }}
          tag_prefix: ${{ steps.getbranch.outputs.safebranch }}-v
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}"
      # Since we are running a powershell script we have to specify the "shell" parameter. The default is "bash".
      - name: Run publish.ps1
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "GitHub Actions"
          if ($env:GITHUB_EVENT_NAME -eq "push") {
            build-scripts/publish.ps1 -VersionNumber "${{ steps.semver.outputs.version }}" -BuildAll $True -Tag "v${{ steps.semverpr.outputs.version }}"
          }
          else {
            build-scripts/publish.ps1 -VersionNumber "${{ steps.semverpr.outputs.version }}-${{ steps.getbranch.outputs.safebranch }}" -Tag "${{ steps.getbranch.outputs.safebranch }}-v${{ steps.semverpr.outputs.version }}"
          }
        shell: pwsh
    env:
      # Be sure to update these with the appropriate Github secrets for your team. Do not paste actual values here.
      ARTIFACTORY_PULL_REGISTRY: "${{ secrets.ARTIFACTORY_PULL_REGISTRY }}"
      ARTIFACTORY_NUGET_REGISTRY: "${{ secrets.CORPDEV_ARTIFACTORY_NUGET_REGISTRY }}"
      ARTIFACTORY_NPM_REGISTRY: "${{ secrets.CORPDEV_ARTIFACTORY_NPM_REGISTRY }}"
      ARTIFACTORY_PUSH_REGISTRY: "${{ secrets.CORPDEV_ARTIFACTORY_PUSH_REGISTRY }}"
      ARTIFACTORY_USERNAME: "${{ secrets.CORPDEV_ARTIFACTORY_USERNAME }}"
      ARTIFACTORY_PASSWORD: "${{ secrets.CORPDEV_ARTIFACTORY_PASSWORD }}"
      ARTIFACTORY_TOKEN: "${{ secrets.CORPDEV_ARTIFACTORY_TOKEN }}"
