name: Run model and task related PyTests
on:
  pull_request:
    paths:
      - 'matsciml/models/**'
  workflow_dispatch:
jobs:
  init:
    uses: ./.github/workflows/make_env.yml
  models-pytest:
    steps:
      - name: Run pytest in models
        run: |
          pytest -v -m "not lmdb and not slow and not remote_request" ./matsciml/models
