name: "Semgrep"

on:
  push:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - run: semgrep scan --sarif --output=semgrep.sarif
        env:
          SEMGREP_RULES: >-
            p/phpcs-security-audit
            p/security-audit
            p/secrets
            p/owasp-top-ten
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
          SEMGREP_REPO_NAME: "auth0/auth0-PHP"
          SEMGREP_REPO_URL: "https://github.com/auth0/auth0-PHP"
