name: shellcheck
on:
  push:
    branches:
      - main
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: shellcheck
      uses: cfy9/shellcheck-action@v0.0.4
